language: python
python:
  - "3.5"
  - "3.6"

env:
  - PILLOW=4.3.*
  - PILLOW=5.0.*
  - PILLOW=5.1.*
  - PILLOW=5.2.*
  - PILLOW=5.3.*
  - PILLOW=5.4.*

# Enable 3.7 without globally enabling sudo and dist: xenial for other build jobs
# See https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true

install:
  - pip install pytest Pillow==$PILLOW
  - pip install -e .
script:
  - pytest tests/
